version: '3.8'

services:
  db:
    image: postgres:15.3
    volumes:
      - type: bind
        source: ./db_up.sql
        target: /docker-entrypoint-initdb.d/setup.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=31415926

  goserver:
    build: ./golang_server/
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080