version: '3.8'

services:
  db:
    image: postgres:15.3
    volumes:
      - type: bind
        source: ./db_up.sql
        target: /docker-entrypoint-initdb.d/setup.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=31415926
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  goserver:
    build: ./golang_server/
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.22
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - goserver
  
  client:
    build: ./astro_client/
    ports:
      - 3000:3000
      
  ssl:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email ikalinin01@mail.ru -d visoff.ru -d api.visoff.ru -d www.visoff.ru --agree-tos