name: deploy on remote server

on: [push, pull_request]
jobs:
    build:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - name: deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    cd /home/ilya/messenger
                    git pull github main
                    docker compose down
                    docker image rm $(docker image ls -a -q)
                    docker compose up -d